version: '3.8'
services:
  frontend:
    build: ./public
    ports:
      - 80:80
  backend:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:latest
    ports: 27018:27017
